spring:
  application:
    name: enrollment-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5332/enrollment_service
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/online-learning-platform
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8181/realms/online-learning-platform
            user-name-attribute: preferred_username
        registration:
          greetings-app-authorization-code:
            provider: keycloak
            client-id: platform-client
            client-secret: zr9XV6I7gDE13aM6Et2NJ6XAXxAzdrpB
            scope:
              - openid
              - microprofile-jwt

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

server:
  port: 8081