version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5332:5432"
    restart: unless-stopped
    networks:
      - microservice_network

  mongodb-keycloak-new-version:
    container_name: mongodb-keycloak-new-version
    image: mongo:latest
    environment:
      MONGODB_INIT_DB: keycloak
    volumes:
      - mongodb-keycloak-provider:/data/db
    ports:
      - "27017:27017"
    networks:
      - microservice_network

  keycloak-new-version:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-new-version
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./config/keycloak:/opt/keycloak/data/import
      - ./custom-keycloak-user-provider/target/custom-provider.jar:/opt/keycloak/providers/custom-provider.jar
      - ./keycloak/theme:/opt/keycloak/themes
    networks:
      - microservice_network

  discovery-server:
    image: bhoper/discovery-server:latest
    container_name: discovery-server
    pull_policy: always
    ports:
      - "8761:8761"
    networks:
      - microservice_network

  course-service:
    image: bhoper/course-service:latest
    container_name: course-service
    pull_policy: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - KEYCLOAK_AUTH_SERVER_URL=http://keycloak-new-version:8080/auth
    depends_on:
      - keycloak-new-version
      - mongodb-keycloak-new-version
      - discovery-server
    networks:
      - microservice_network

  enrollment-service:
    image: bhoper/enrollment-service:latest
    container_name: enrollment-service
    pull_policy: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/enrollment_service
      - KEYCLOAK_AUTH_SERVER_URL=http://keycloak-new-version:8080/auth
    depends_on:
      - postgres
      - discovery-server
      - keycloak-new-version
    networks:
      - microservice_network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/myconf.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend-service
      - keycloak-new-version
    networks:
      - microservice_network

  frontend-service:
    image: bhoper/frontend-service:latest
    container_name: frontend-service
    pull_policy: always
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
      - KEYCLOAK_AUTH_SERVER_URL=http://keycloak-new-version:8080/auth
    depends_on:
      - keycloak-new-version
      - discovery-server
#    extra_hosts:
#      - "keycloak-new-version:192.168.100.39"
    networks:
      - microservice_network

  user-service:
    image: bhoper/user-service:latest
    container_name: user-service
    pull_policy: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-server:8761/eureka/
    depends_on:
      - keycloak-new-version
      - mongodb-keycloak-new-version
      - discovery-server
    networks:
      - microservice_network


networks:
  microservice_network:
    driver: bridge

volumes:
  mongodb-keycloak-provider:
  postgres: