version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - microservice_network
    restart: unless-stopped

  mongodb-keycloak-new-version:
    container_name: mongodb-keycloak-new-version
    image: mongo:latest
    environment:
      MONGODB_INIT_DB: keycloak
    volumes:
      - mongodb-keycloak-provider:/data/db
    ports:
      - "27017:27017"

  keycloak-new-version:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-new-version
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8181:8080"
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./config/keycloak:/opt/keycloak/data/import
      - ./custom-keycloak-user-provider/target/custom-provider.jar:/opt/keycloak/providers/custom-provider.jar
      - ./keycloak/theme:/opt/keycloak/themes

networks:
  microservice_network:
    driver: bridge

volumes:
  mongodb-keycloak-provider:
  postgres: