spring:
  application:
    name: course-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/course-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/online-learning-platform