spring:
  application:
    name: course-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/course-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak-new-version:8080/realms/online-learning-platform/protocol/openid-connect/certs
          issuer-uri: http://keycloak-new-version:8080/realms/online-learning-platform

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true


server:
  port: 8081