spring:
  application:
    name: course-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/course-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8181/realms/online-learning-platform/protocol/openid-connect/certs
          issuer-uri: http://localhost:8181/realms/online-learning-platform

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

server:
  port: 8080