spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://nginx/realms/online-learning-platform
            user-name-attribute: preferred_username
        registration:
          greetings-app-authorization-code:
            provider: keycloak
            client-id: platform-client
            client-secret: KDIF7w8LKZCRuaEZPvqrrsKzVyXzNyud
            scope:
              - openid
              - microprofile-jwt
              - email
              - profile
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/

server:
  port: 8083