spring:
  application:
    name: frontend-service
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8181/realms/online-learning-platform
            user-name-attribute: preferred_username
        registration:
          greetings-app-authorization-code:
            provider: keycloak
            client-id: platform-client
            client-secret: xz1r4PRmjUs3W6sa9eiVBcezS8Y8jPxH
            scope:
              - openid
              - microprofile-jwt

server:
  port: 8082